### ISSUE TITLE
Octoprint login broken after 1.8.3 (CSRF validation failed)

### ISSUE THREAD

**Issue by pooyashahidi** [MaxWinterstein/homeassistant-addons#115]
Hi,

The octoprint proxy stopped workingy with 1.8.3. It is not possible to login anymore: CSRF validation failed
Is there any way to implement a fix for this?

my addon config:
```yaml
octoprint_host: 172.30.33.222
octoprint_port: 5000
ssl:
  enabled: false
  verify: false
```

thank you :)

Here is a blog post related to the change.
https://community.octoprint.org/t/i-can-no-longer-login-after-upgrading-to-1-8-3-and-im-accessing-octoprint-through-a-reverse-proxy/46843
